services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:0.29.1
    container_name: fckwp-cms
    restart: unless-stopped
    ports:
      - "9000:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
      - ./pocketbase/pb_hooks:/pb_hooks
      - ./pocketbase/pb_public:/pb_public